# Generated by Django 6.0 on 2025-12-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Experience', models.IntegerField()),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
